# Generated by Django 5.1.8 on 2025-04-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000')),
            ],
        ),
    ]
