# Generated by Django 5.1.8 on 2025-04-13 13:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0002_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
